### ISSUE TITLE
Issue when open video via url

### ISSUE THREAD

**Issue by Harpreetcompetent** [igormidev/youtube_shorts#11]
YoutubeExplodeException: Video LRUmpK9Umo8 returned 403 (stream: 18
E/flutter ( 9565): #0      StreamClient.getManifest.<anonymous closure> (package:youtube_shorts/youtube_explode_fork/src/videos/streams/stream_client.dart:185:9)
E/flutter ( 9565): <asynchronous suspension>
E/flutter ( 9565): #1      retry (package:youtube_shorts/youtube_explode_fork/src/retry.dart:16:14)
E/flutter ( 9565): <asynchronous suspension>
E/flutter ( 9565): #2      VideosSourceController.getVideoInfoFromVideoModel (package:youtube_shorts/src/source/interface_videos_source_controller.dart:101:9)
E/flutter ( 9565): <asynchronous suspension>
E/flutter ( 9565): #3      VideosSourceControllerFromUrlList.getVideoByIndex.<anonymous closure> (package:youtube_shorts/src/source/impl_from_url_list.dart:25:36)
E/flutter ( 9565): <asynchronous suspension>
E/flutter ( 9565): #4      isolateEntry (package:easy_isolate_mixin/src/run_isolate_entry.dart:17:18)
E/flutter ( 9565): <asynchronous suspension>

**Comment by ikidhann** [comment]
I got the same error

**Comment by rony1235** [comment]
I got the same error

**Comment by dossanovruslan** [comment]
I got the same error

**Comment by rony1235** [comment]
update video_controller file then it work

```
static const _androidSuiteClient = {
    'context': {
      'client': {
        'clientName': 'ANDROID_CREATOR',
        'clientVersion': '24.24.100',
        'androidSdkVersion': 30,
        'hl': 'en',
        'gl': 'US',
        'utcOffsetMinutes': 0,
      },
    },
  };
```
