### ISSUE TITLE
YoutubeExplodeException: Video PiWJWfzVwjU returned 403 (stream: 18

### ISSUE THREAD

**Issue by Harpreetcompetent** [igormidev/youtube_shorts#12]
YoutubeExplodeException: Video PiWJWfzVwjU returned 403 (stream: 18
E/flutter (21519): #0      StreamClient.getManifest.<anonymous closure> (package:youtube_shorts/youtube_explode_fork/src/videos/streams/stream_client.dart:46:9)
E/flutter (21519): <asynchronous suspension>
E/flutter (21519): #1      retry (package:youtube_shorts/youtube_explode_fork/src/retry.dart:16:14)
E/flutter (21519): <asynchronous suspension>
E/flutter (21519): #2      VideosSourceController.getVideoInfoFromVideoModel (package:youtube_shorts/src/source/interface_videos_source_controller.dart:101:9)
E/flutter (21519): <asynchronous suspension>
E/flutter (21519): #3      VideosSourceControllerFromUrlList.getVideoByIndex.<anonymous closure> (package:youtube_shorts/src/source/impl_from_url_list.dart:25:36)
E/flutter (21519): <asynchronous suspension>
E/flutter (21519): #4      isolateEntry (package:easy_isolate_mixin/src/run_isolate_entry.dart:17:18)

**Comment by masdaagus** [comment]
i have the sampe error, did you find how to handle this issue?
